package io.spherelabs.blahblahfake.provider

import io.spherelabs.blahblahfake.annotation.BlahBlahInternalApi

@BlahBlahInternalApi
internal enum class ProviderType {
    Address,
    Animal,
    App,
    University,
    Artist,
    Company,
    Compass,
    Internet,
    Lorem,
    Hipster,
    Name,
    CreditCard,
    Color,
    Commerce,
    Team,
    Hacker,
    IdNumber,
    Emoji,
    Book,
    Cat,
    SuperHero,
    Code,
    ChuckNorris,
    Educator,
    Space,
    Yoda,
    Music,
    File,
    GameOfThrones,
    Pokemon,
    Food,
    Esports,
    Ancient,
    TwinPeaks,
    LordOfTheRings,
    Zelda,
    RockBand,
    Job,
    Dessert,
    Demographic,
    Friends,
    RickyAndMorty,
    Quote
}
